apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jyothsnav/my-app:0432fa4184973b05c8840d78e7e0dda258dafe20
        ports:
        - containerPort: 3000

