apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jyothsnav/my-app:6108be3b5522eaec16859ce34f27ddb90b161d4c
        ports:
        - containerPort: 3000

