apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: jyothsnav/my-app:cbfed4dd1f4edd1f8c24cf346649cad587ed2340
        ports:
        - containerPort: 3000

